spring.application.name=earthquakeApp

spring.datasource.url=jdbc:postgresql://ep-plain-sky-anm80zoo-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mPDe6nNJR7TU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true